name: vcd-api-tools CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [ closed ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Check source license headers
      run: mvn license:check-file-header -Dlicense.licenseName=bsd_2 -Dlicense.failOnNotUptodateHeader=true -Dlicense.failOnMissingHeader=true
    - name: Build with Maven
      run: mvn -B package --file pom.xml
  Branch-Creation:
    #this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo "title ${{github.event.pull_request.title}}."
      - name: checkout repository code
        uses: actions/checkout@v2
      - name: condition checking
        run: |
          VERSION=`echo ${{github.event.pull_request.title}} | cut -d " " -f 4`
          desc="Pull Request for $VERSION tools release"
          MASTER_BRANCH_NAME=`git rev-parse --abbrev-ref HEAD`
          existed=$(git ls-remote --heads origin ${VERSION})
          echo "$MASTER_BRANCH_NAME"
          echo "$VERSION"
          echo "$desc"
          echo "${{github.event.pull_request.title}}"
          if [ "${{ github.event.pull_request.title }}" == "$desc" ] && [ -z ${existed} ]; 
          then
            git pull
            git status
            git checkout -b $VERSION
            git push -u origin $VERSION
            git branch
          elif [ "${{ github.event.pull_request.title }}" == "$desc" ];
          then
            git config --global user.email "sridhar.meesala2000@gmail.com"
            git config --global user.name "${{ github.actor }}"
            echo "--branchname---"
            git branch
            echo "---- git pull ----------"
            git pull
            echo "---- git log -1 --------"
            git log -1
            echo "---- git checkout --track origin/$VERSION ----"
            git checkout --track origin/$VERSION
            echo "---- git branch ---------"
            git branch
            echo "---- git pull -----------"
            git pull
            echo "----- git log -1 --------"
            git log -1
            echo "----- git merge origin/$MASTER_BRANCH_NAME ------"
            git reset --hard $MASTER_BRANCH_NAME
            echo "---- git push ----------"
            git push --force origin $VERSION
          else
            echo "No Branch creation"
          fi
